### PR TITLE
Responsive navbar

### PR DESCRIPTION
**Pull request by dipshojol**
scalable navbar

### CODE REVIEW

**Review by aeciorc — APPROVED** [review]
I won't have time to actually run this, but assuming it's like what you demo earlier, should be good to go

**Comment by dipshojol** [comment]
> I won't have time to actually run this, but assuming it's like what you demo earlier, should be good to go

Screen Shot 2019-11-29 at 12 42 34 PM
Screen Shot 2019-11-29 at 12 42 17 PM

**Review by aeciorc — APPROVED** [review]
Ok looks good to me!

**Comment by dipshojol** [comment]
> Ok looks good to me!

one small issue. the post-close button is white, in white poster, the button hardly can be seen. do you have any recommendation

**Pull request merged**
